# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

# Require react-native-permissions setup
require_relative '../node_modules/react-native-permissions/scripts/setup'

platform :ios, '15.5'
prepare_react_native_project!

# VisionCamera v4 works without use_frameworks!
target 'AIPhotoCoach' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )
  
  # Setup react-native-permissions
  setup_permissions([
    'Camera',
    'PhotoLibrary',
    'PhotoLibraryAddOnly',
    'Motion',
  ])

  post_install do |installer|
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.5'
      end
    end
  end
end
